# Generated by Django 4.0.5 on 2022-06-04 15:05

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('main_habit', '0002_statistics_profile'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='profile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['user'], name='main_habit__user_id_8a45b2_gin'),
        ),
        migrations.AddIndex(
            model_name='statistics',
            index=django.contrib.postgres.indexes.GinIndex(fields=['time', 'is_done', 'habit', 'profile'],
                                                           name='main_habit__time_618f0a_gin'),
        ),
    ]
